name: Build Desktop App
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Получение исходного кода
      uses: actions/checkout@v3

    - name: Установка Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Установка зависимостей
      run: npm install

    - name: Компиляция приложения
      run: npm run build

    - name: Загрузка EXE как Артефакта
      uses: actions/upload-artifact@v4
      with:
        name: Schematizer-Pro-EXE
        path: dist/*.exe
