name: Build Desktop App
on: [push] # Сборка при каждом сохранении кода

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # Разрешение на публикацию релиза
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with: { node-version: '18' }
    - run: npm install
    - run: npm run build
    - name: Update Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.exe
        tag_name: v1.0.0-mvp
        append_body: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
